migrated to null-safety #12
joshuadeguzman/flutter_moviehub pull request #19
Opened 2021-08-07 05:15 UTC by M-A-D-A-R-A

[#12](https://github.com/joshuadeguzman/flutter-examples/issues/12)

Please review the changes @joshuadeguzman

2021-08-07 10:02 UTC, joshuadeguzman requested changes
Awesome, thank you @M-A-D-A-R-A! You might need to apply the migrations first to remove the hints coming from the migration tool.

2021-08-07 10:02 UTC, joshuadeguzman commented on flutter_dribbble_nike_sb/lib/widgets/app_cta_button.dart
> +    /*required*/ required this.title,
Might be a leftover hint from the migration tool?

2021-08-07 10:02 UTC, joshuadeguzman commented on flutter_dribbble_nike_sb/lib/widgets/app_cta_button.dart
> +  Function/*!*/ get _onCtaTap => widget.onCtaTap;
Similar to this one, kindly check the rest. Here's a reference that can help you: https://dart.dev/null-safety/migration-guide

2021-08-15 10:26 UTC, joshuadeguzman commented
Hey @M-A-D-A-R-A, I would like to know if you have any updates on this. :D

2021-08-16 03:18 UTC, M-A-D-A-R-A commented
> Hey @M-A-D-A-R-A, I would like to know if you have any updates on this. :D

Yeah sorry i was having my sem exams Ill looking it as soon as i can . Thanks!

2023-05-16 07:36 UTC, closed without merging